   services:
     engine:
       container_name: ai-voice-connector-engine
       build:
         context: ../
         dockerfile: ./docker/Dockerfile
       ports:
         - "5070:5060/udp"  
         - "35000-40000:35000-40000/udp"  # RTP portları
       environment:
         CONFIG_FILE: /app/config.ini
       env_file:
         - .env
       volumes:
         - ../src:/app/src/
         - ../config.ini:/app/config.ini
