services:
  engine:
    container_name: ai-voice-connector-engine
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    network_mode: host
    environment:
      CONFIG_FILE: /app/config.ini
    env_file:
      - .env
    volumes:
      - ../src:/app/src/
      - ../config.ini:/app/config.ini

  opensips:
    container_name: ai-voice-connector-opensips
    image: opensips/opensips:latest
    volumes:
      - ../cfg/:/etc/opensips/
    network_mode: host
